//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webtekno.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class personelbilgi
    {
        public int meslekid { get; set; }
        public string ad { get; set; }
        public Nullable<int> yas { get; set; }
        public string departman { get; set; }
        public string mevki { get; set; }
        public string tecrube { get; set; }
        public string Photo { get; set; }
    }
}
